
switch argument0
{
	case item.Grass:			return "Grass";
	case item.Stick:			return "Stick";
	case item.Small_animal:		return "Small animal";
	case item.Shrub:			return "Shrub";
	case item.Dirt:				return "Dirt";
	case item.Poo:				return "Poo";
	case item.Rock:				return "Rock";
	case item.Ore:				return "Ore";
	case item.Sprout:			return "Sprout";
	case item.Coal:				return "Coal";
	case item.Insect:			return "Insect";
	case item.Bee:				return "Bee";
	case item.Water:			return "Water";
	case item.Long_Grass:		return "Long Grass";
	case item.Medium_Animal:	return "Medium Animal";
	case item.Crop:				return "Crop";
	case item.Moss:				return "Moss";
	case item.Flower:			return "Flower";
	case item.Bundle_of_sticks:	return "Bundle of sticks";
	case item.Corpse:			return "Corpse";
	case item.Poo_stick:		return "Poo stick";
	case item.Rock_axe:			return "Rock axe";
	case item.Mushrooms:		return "Mushrooms";
	case item.Pencil:			return "Pencil";
	case item.Turtle:			return "Turtle";
	case item.Grove:			return "Grove";
	case item.Tree:				return "Tree";
	case item.Marsh:			return "Marsh";
	case item.Fetaliser:		return "Fetaliser";
	case item.Mud:				return "Mud";
	case item.Bigger_poo:		return "Bigger poo";
	case item.Beatle:			return "Beatle";
	case item.Rock_garden:		return "Rock garden";
	case item.Diamond:			return "Diamond";
	case item.Paste:			return "Paste";
	case item.Creek:			return "Creek";
	case item.Swarm:			return "Swarm";
	case item.Wasp:				return "Wasp";
	case item.Hive:				return "Hive";
	case item.Hay_Stack:		return "Hay Stack";
	case item.Bigger_Crops:		return "Bigger Crops";
	case item.Longer_Grass:		return "Longer Grass";
	case item.Preditor:			return "Preditor";
	case item.Larger_Animal:	return "Larger Animal";
	case item.Fossil:			return "Fossil";
	case item.Harvest:			return "Harvest";
	case item.Barren_landscape:	return "Barren Landscape";
	case item.Moss_stick:		return "Moss Stick";
	case item.Flower_field:		return "Flower Field";
	case item.Honey:			return "Honey";
	case item.Fire:				return "Fire";
	case item.Hut:				return "Hut";
	default: return -1;
}