
switch argument0
{
	case "Grass":			return item.Grass;
	case "Stick":			return item.Stick;
	case "Small animal":		return item.Small_animal;
	case "Shrub":			return item.Shrub;
	case "Dirt":				return item.Dirt;
	case "Poo":				return item.Poo;
	case "Rock":				return item.Rock;
	case "Ore":				return item.Ore;
	case "Sprout":			return item.Sprout;
	case "Coal":				return item.Coal;
	case "Insect":			return item.Insect;
	case "Bee":				return item.Bee;
	case "Water":			return item.Water;
	case "Long Grass":		return item.Long_Grass;
	case "Medium Animal":	return item.Medium_Animal;
	case "Crop":				return item.Crop;
	case "Moss":				return item.Moss;
	case "Flower":			return item.Flower;
	case "Bundle of sticks":	return item.Bundle_of_sticks;
	case "Corpse":			return item.Corpse;
	case "Poo stick":		return item.Poo_stick;
	case "Rock axe":			return item.Rock_axe;
	case "Mushrooms":		return item.Mushrooms;
	case "Pencil":			return item.Pencil;
	case "Turtle":			return item.Turtle;
	case "Grove":			return item.Grove;
	case "Tree":				return item.Tree;
	case "Marsh":			return item.Marsh;
	case "Fetaliser":		return item.Fetaliser;
	case "Mud":				return item.Mud;
	case "Bigger poo":		return item.Bigger_poo;
	case "Beatle":			return item.Beatle;
	case "Rock garden":		return item.Rock_garden;
	case "Diamond":			return item.Diamond;
	case "Paste":			return item.Paste;
	case "Creek":			return item.Creek;
	case "Swarm":			return item.Swarm;
	case "Wasp":				return item.Wasp;
	case "Hive":				return item.Hive;
	case "Hay Stack":		return item.Hay_Stack;
	case "Bigger Crops":		return item.Bigger_Crops;
	case "Longer Grass":		return item.Longer_Grass;
	case "Preditor":			return -1;
	case "Large Animal":		return -1;
	case "Fossil":			return -1;
	case "Harvest":			return -1;
	case "Barren":	return -1;
	case "Moss Stick":		return	-1;
	default: return -1;
}